server:
  port: 18400
spring:
  profiles:
    active: dev
    include:
      - feign
      - redis
  application:
    name: exchange-service-auth
  cloud:
    nacos:
      username: nacos
      password: LawZhuo1002.
      discovery:
        server-addr: 106.12.183.54:8848
        namespace: 09a6d4e7-6ba4-410c-9451-822410f9fbe6
      config:
        server-addr: 106.12.183.54:8848
        file-extension: yaml
        refresh-enabled: true
        namespace: 09a6d4e7-6ba4-410c-9451-822410f9fbe6

  config:
    import:
      - nacos:exchange-config-redis.yml?group=CONFIG_GROUP

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

exchange:
  doc:
    title: Crypto Exchange Auth API
    description: 认证服务接口文档
    version: 1.0
