server:
  port: 8081
spring:
  profiles:
    active: dev
    include:
      - feign
      - db
      - redis
  application:
    name: service-uc

bt:
  upstream:
    base-url: ${BT_UPSTREAM_BASE_URL:http://localhost:8080}
