spring:
  rabbitmq:
    host: ${RABBITMQ.HOST}
    port: ${RABBITMQ.PORT}
    username: ${RABBITMQ.USERNAME}
    password: ${RABBITMQ.PASSWORD}
    virtual-host: ${RABBITMQ.EMAIL_VIRTUAL_HOST:/}
    connection-timeout: ${RABBITMQ.CONNECTION_TIMEOUT}
    requested-heartbeat: ${RABBITMQ.REQUESTED_HEARTBEAT}
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10
        retry:
          enabled: false

exchange:
  rabbitmq:
    queues:
      - name: queue.email.send
        exchange: exchange.notification
        routing-key: email.send
        dlx-exchange: exchange.notification.dlx
        dlx-routing-key: email.send.dlx
        dlx-queue: queue.email.send.dlx
