server:
  port: 18461
spring:
  profiles:
    active: dev
    include:
      - binance
      - redis
      - mq
  application:
    name: exchange-service-datasource
  cloud:
    nacos:
      username: nacos
      password: LawZhuo1002.
      discovery:
        server-addr: 106.12.183.54:8848
        namespace: ${NACOS_NAMESPACE:crypto-exchange-local}
      config:
        server-addr: 106.12.183.54:8848
        file-extension: yaml
        refresh-enabled: true
        namespace: ${NACOS_NAMESPACE:crypto-exchange-local}
  config:
    import:
      - nacos:exchange-config-redis.yml?group=CONFIG_GROUP
      - nacos:exchange-config-rabbitmq.yml?group=CONFIG_GROUP
