server:
  port: ${EXCHANGE_ADMIN_PORT:18301}

spring:
  application:
    name: exchange-admin
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration
      - com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration
  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:LawZhuo1002.}
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:106.12.183.54:8848}
        namespace: ${NACOS_NAMESPACE:crypto-exchange-local}
      config:
        server-addr: ${NACOS_SERVER_ADDR:106.12.183.54:8848}
        namespace: ${NACOS_NAMESPACE:crypto-exchange-local}
        file-extension: yaml
  config:
    import:
      - optional:nacos:exchange-admin.yml?group=ADMIN_GROUP

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
