server:
  port: 8081
spring:
  profiles:
    active: dev
    include:
      - feign
      - db
  application:
    name: user-route

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
