server:
  port: 18471
spring:
  profiles:
    active: dev
    include:
      - feign
      - db
      - redis
  application:
    name: business-user
  cloud:
    nacos:
      username: nacos
      password: LawZhuo1002.
      discovery:
        server-addr: 106.12.183.54:8848
        namespace: 09a6d4e7-6ba4-410c-9451-822410f9fbe6
      config:
        server-addr: 106.12.183.54:8848
        file-extension: yaml
        refresh-enabled: true
        namespace: 09a6d4e7-6ba4-410c-9451-822410f9fbe6
  config:
    import:
      - nacos:exchange-config-database.yml?group=CONFIG_GROUP
      - nacos:exchange-config-redis.yml?group=CONFIG_GROUP
