server:
  port: 18471
spring:
  profiles:
    active: dev
    include:
      - feign
      - db
      - redis
  application:
    name: exchange-business-user
  cloud:
    nacos:
      username: nacos
      password: LawZhuo1002.
      discovery:
        server-addr: 106.12.183.54:8848
        namespace: ${NACOS_NAMESPACE:crypto-exchange-local}
      config:
        server-addr: 106.12.183.54:8848
        file-extension: yaml
        refresh-enabled: true
        namespace: ${NACOS_NAMESPACE:crypto-exchange-local}
  config:
    import:
      - nacos:exchange-config-database.yml?group=CONFIG_GROUP
      - nacos:exchange-config-redis.yml?group=CONFIG_GROUP
