spring:
  cloud:
    gateway:
      # cors配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        # 行情 WebSocket 统一入口
        - id: exchange-market-websocket-route
          uri: lb:ws://exchange-business-market
          predicates:
            - Path=/ws/market

        # 用户端统一接口
        - id: exchange-web-route
          uri: lb://exchange-web
          predicates:
            - Path=/api/crypto-exchange/web/**
          filters:
            - StripPrefix=3

        # 后台统一接口
        - id: exchange-admin-route
          uri: lb://exchange-admin
          predicates:
            - Path=/api/crypto-exchange/admin/**
          filters:
            - StripPrefix=3
