spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:106.12.183.54}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:ChangeMe_2026!}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:vhost_market}
    connection-timeout: 15000
    requested-heartbeat: 30
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 200
        retry:
          enabled: false

exchange:
  rabbitmq:
    queues:
      - name: queue.market.data.business
        exchange: exchange.market.data
        routing-key: market.binance.#
        dlx-exchange: exchange.market.data.dlx
        dlx-routing-key: market.binance.dlx
        dlx-queue: queue.market.data.business.dlx
