spring:
  rabbitmq:
    host: ${RABBITMQ.HOST}
    port: ${RABBITMQ.PORT}
    username: ${RABBITMQ.USERNAME}
    password: ${RABBITMQ.PASSWORD}
    virtual-host: ${RABBITMQ.MARKET_VIRTUAL_HOST:/}
    connection-timeout: ${RABBITMQ.CONNECTION_TIMEOUT}
    requested-heartbeat: ${RABBITMQ.REQUESTED_HEARTBEAT}
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 200
        retry:
          enabled: false

exchange:
  rabbitmq:
    queues:
      - name: ${RABBITMQ.MARKET.DATA_QUEUE} # 业务队列
        exchange: ${RABBITMQ.MARKET.DATA_EXCHANGE} # 交换机
        routing-key: ${RABBITMQ.MARKET.DATA_ROUTING_KEY} # 绑定规则
        dlx-exchange: ${RABBITMQ.MARKET.DATA_DLX_EXCHANGE}
        dlx-routing-key: ${RABBITMQ.MARKET.DATA_DLX_ROUTING_KEY}
        dlx-queue: ${RABBITMQ.MARKET.DATA_DLX_QUEUE}
