spring:
  data:
    redis:
      host: ${DATABASE.REDIS.HOST}
      port: ${DATABASE.REDIS.PORT}
      password: ${DATABASE.REDIS.PASSWORD}
      database: ${DATABASE.REDIS.DATABASE}
      timeout: ${DATABASE.REDIS.TIMEOUT}
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 2
          max-wait: 3000ms
