spring:
  rabbitmq:
    host: ${RABBITMQ.HOST:106.12.183.54}
    port: ${RABBITMQ.PORT:5672}
    username: ${RABBITMQ.USERNAME:admin}
    password: ${RABBITMQ.PASSWORD:ChangeMe_2026!}
    virtual-host: ${RABBITMQ.VIRTUAL_HOST:vhost_market}
    connection-timeout: ${RABBITMQ.CONNECTION_TIMEOUT:5000}
    requested-heartbeat: ${RABBITMQ.REQUESTED_HEARTBEAT:60}
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 200
        retry:
          enabled: false

exchange:
  rabbitmq:
    queues:
      - name: ${RABBITMQ.MARKET.DATA_QUEUE} # 业务队列
        exchange: ${RABBITMQ.MARKET.DATA_EXCHANGE} # 交换机
        routing-key: ${RABBITMQ.MARKET.DATA_ROUTING_KEY} # 绑定规则
        dlx-exchange: ${RABBITMQ.MARKET.DATA_DLX_EXCHANGE}
        dlx-routing-key: ${RABBITMQ.MARKET.DATA_DLX_ROUTING_KEY}
        dlx-queue: ${RABBITMQ.MARKET.DATA_DLX_QUEUE}
