server:
  port: ${SPOT_PORT:18473}

spring:
  application:
    name: exchange-business-spot
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    include:
      - feign
      - db
  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:LawZhuo1002.}
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:106.12.183.54:8848}
        namespace: ${NACOS_NAMESPACE:09a6d4e7-6ba4-410c-9451-822410f9fbe6}
      config:
        server-addr: ${NACOS_SERVER_ADDR:106.12.183.54:8848}
        namespace: ${NACOS_NAMESPACE:09a6d4e7-6ba4-410c-9451-822410f9fbe6}
        file-extension: yaml
  config:
    import:
      - optional:nacos:exchange-config-database.yml?group=CONFIG_GROUP

management:
  endpoints:
    web:
      exposure:
        include: health,info

spot:
  fee_rate: 0.005
