server:
  port: ${SPOT_PORT:18473}

spring:
  application:
    name: exchange-business-spot
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    include:
      - feign
      - db
      - redis
  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:LawZhuo1002.}
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:106.12.183.54:8848}
        namespace: ${NACOS_NAMESPACE:crypto-exchange-local}
      config:
        server-addr: ${NACOS_SERVER_ADDR:106.12.183.54:8848}
        namespace: ${NACOS_NAMESPACE:crypto-exchange-local}
        file-extension: yaml
  config:
    import:
      - nacos:exchange-config-database.yml?group=CONFIG_GROUP
      - nacos:exchange-config-redis.yml?group=CONFIG_GROUP

management:
  endpoints:
    web:
      exposure:
        include: health,info

spot:
  fee_rate: 0.005
