spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: lawzhuo@qq.com
    password: bwezkusbvdzdcbcc  # QQ邮箱生成的【授权码】

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp